spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: "jdbc:postgresql://${POSTGRES_HOST}:5432/test_app"
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver